[package]
org = "laf"
name = "testcontainers"
version = "1.15.3001"
license = ["Apache-2.0"]
authors = ["laf"]
repository = "https://github.com/lafernando/testcontainers"
keywords = ["ballerina", "test", "testcontainers", "containers"]

[build-options]
observabilityIncluded = false

[[platform.java11.dependency]]
groupId = "org.testcontainers"
artifactId = "postgresql"
version = "1.15.3"

# transitive dependency of org.testcontainers:postgresql:1.15.3
[[platform.java11.dependency]]
groupId = "org.testcontainers"
artifactId = "jdbc"
version = "1.15.3"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.testcontainers"
artifactId = "database-commons"
version = "1.15.3"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.testcontainers"
artifactId = "testcontainers"
version = "1.15.3"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "junit"
artifactId = "junit"
version = "4.12"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.hamcrest"
artifactId = "hamcrest-core"
version = "1.3"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "1.7.30"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.20"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.rnorth.duct-tape"
artifactId = "duct-tape"
version = "1.0.8"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "org.rnorth.visible-assertions"
artifactId = "visible-assertions"
version = "2.1.2"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "net.java.dev.jna"
artifactId = "jna"
version = "5.2.0"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "com.github.docker-java"
artifactId = "docker-java-api"
version = "3.2.8"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.10.3"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "com.github.docker-java"
artifactId = "docker-java-transport-zerodep"
version = "3.2.8"

# transitive dependency of org.testcontainers:jdbc:1.15.3
[[platform.java11.dependency]]
groupId = "com.github.docker-java"
artifactId = "docker-java-transport"
version = "3.2.8"
